/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a citizen account
         * @description Self-registration always creates a `citizen`. Staff and admin accounts are
         *     created by an admin via `POST /api/admin/users`; a `role` sent here is
         *     ignored rather than honoured, so this endpoint cannot be used to escalate.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Account created. Does not log the user in. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                409: components["responses"]["Conflict"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a session
         * @description Sets an HttpOnly, Secure, SameSite=Lax session cookie. No token is
         *     returned in the body, and nothing is stored in `localStorage`. A token
         *     readable by JavaScript is XSS-exposed.
         *
         *     The body is form-encoded, not JSON, and the email goes in the `username`
         *     field. This is the one deviation from the JSON convention: it matches the
         *     `fastapi-users` default so the login route needs no custom code.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Session established; cookie set. */
                204: {
                    headers: {
                        /** @example gabai_session=...; HttpOnly; Secure; SameSite=Lax; Path=/ */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad credentials, or the account is deactivated. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session cleared. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The authenticated user. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List requests, scoped to the caller's role
         * @description Scope is applied server-side and cannot be widened by query parameters:
         *
         *     - **citizen**, only their own requests
         *     - **staff**, requests assigned to them, plus requests in a category they
         *       hold an active routing rule for, plus everything in `under_review`. The
         *       union matters twice: deactivating a rule must not strip a staff member
         *       of requests already assigned to them, and a request awaiting manual
         *       classification cannot be scoped by a category that does not exist yet.
         *     - **admin**, all requests
         *
         *     The `under_review` clause is a deliberate widening of least privilege.
         *     Unclassified requests are visible to all staff because the category that
         *     would otherwise scope them is exactly what is in doubt; every review
         *     decision is attributed in the audit log.
         *
         *     Default ordering is role-dependent and chosen by the server, not the
         *     client. Staff and admin get highest urgency first, then oldest first,
         *     which is the order the queue is worked in. Citizens get newest first, because
         *     a resident opening their list is looking for the request they just
         *     filed, not the most urgent one.
         */
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["Limit"];
                    offset?: components["parameters"]["Offset"];
                    /** @description Repeat the parameter to match any of several statuses. */
                    status?: components["schemas"]["RequestStatus"][];
                    category_id?: number;
                    urgency?: components["schemas"]["Urgency"];
                    /** @description Case-insensitive substring match on description and reference number. */
                    q?: string;
                    sort?: "urgency_desc" | "created_asc" | "created_desc" | "updated_desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of requests. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedResponse"] & {
                            items?: components["schemas"]["RequestSummary"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /**
         * Submit a request
         * @description Persists the request and returns it immediately with status `submitted`
         *     and a reference number. Classification runs after the response, so the
         *     citizen never waits on inference; poll the detail endpoint (or watch
         *     notifications) for the classified result.
         *
         *     Only authenticated citizens may submit.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RequestCreate"];
                };
            };
            responses: {
                /** @description Accepted and persisted. Not yet classified. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Request"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        /**
         * Request detail
         * @description Same role scoping as `GET /api/requests`, including the `under_review`
         *     clause. Otherwise every row in the review queue would 404 on click.
         *
         *     Returns 404, not 403, when the request exists but is outside the caller's
         *     scope. A 403 would confirm the id is real and let a staff member map
         *     requests outside their categories by probing ids.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    request_id: components["parameters"]["RequestId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The request, with its status history and attachments. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Request"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{request_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change status
         * @description Staff and admin only. Writes a `status_history` row and an audit entry,
         *     and notifies the citizen. Illegal transitions are rejected with 409.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    request_id: components["parameters"]["RequestId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StatusUpdate"];
                };
            };
            responses: {
                /** @description Updated request. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Request"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description Not a legal transition from the current status. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                422: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/api/requests/{request_id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Attach a file
         * @description The owning citizen, or staff assigned to the request. MIME type and size
         *     are validated server-side against the declared allowlist. The `accept`
         *     attribute on a file input is a hint to the user, not a control.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    request_id: components["parameters"]["RequestId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description Stored. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Attachment"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description File exceeds the maximum size. */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description MIME type not allowed. */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{request_id}/attachments/{attachment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: components["parameters"]["RequestId"];
                attachment_id: number;
            };
            cookie?: never;
        };
        /**
         * Download an attachment
         * @description Scoped exactly as the parent request, so a file is never reachable by
         *     anyone who cannot see the request itself. Served through the API rather
         *     than as a static URL. `stored_path` is deliberately not exposed, so an
         *     unguessable-URL scheme is not standing in for an access check.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    request_id: components["parameters"]["RequestId"];
                    attachment_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description File contents. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": string;
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Requests awaiting manual classification
         * @description Staff and admin. Requests whose lower confidence score fell below the
         *     threshold and which therefore have status `under_review`. Oldest first, because
         *     this queue is a backlog and urgency here is not yet trustworthy.
         */
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["Limit"];
                    offset?: components["parameters"]["Offset"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of requests needing a human label. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedResponse"] & {
                            items?: components["schemas"]["RequestSummary"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{request_id}/classification": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set the final category and urgency
         * @description Staff and admin. Sets `final_category_id` and `final_urgency`, then
         *     re-runs routing.
         *
         *     Works on **any** request the caller can see, not only items in the review
         *     queue, because the case where correction matters most is when the model
         *     was confident and wrong, and that request never reaches the queue. The
         *     model's original prediction is never overwritten, so every correction
         *     stays measurable against it.
         *
         *     **Re-routing can hand the request to someone else.** Changing the
         *     category re-runs the routing rules, so a request may be reassigned to a
         *     different staff member, after which the correcting staff member no
         *     longer sees it, because it is no longer theirs. That is intended: they
         *     handed it off. The citizen is notified of the reassignment.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    request_id: components["parameters"]["RequestId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReviewDecision"];
                };
            };
            responses: {
                /** @description Labelled and routed. `assigned_staff` may differ from before the call. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Request"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /**
                 * @description Request is `resolved` or `closed`. A finished request is not
                 *     relabelled. Re-routing one would resurrect it into an active queue.
                 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                422: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List categories
         * @description The single source of category values for the whole system. Clients render
         *     whatever this returns; the taxonomy can change without a frontend release.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Admin only. Retired categories still appear on historical requests. */
                    include_inactive?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Categories, ordered by name. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's notifications */
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["Limit"];
                    offset?: components["parameters"]["Offset"];
                    unread_only?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of notifications, newest first. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedResponse"] & {
                            items?: components["schemas"]["Notification"][];
                            /** @description Total unread for this user, independent of paging. */
                            unread_count: number;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark as read */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    notification_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Updated notification. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Notification"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List accounts */
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["Limit"];
                    offset?: components["parameters"]["Offset"];
                    role?: components["schemas"]["Role"];
                    is_active?: boolean;
                    /** @description Case-insensitive substring match on email and full name. */
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of accounts. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedResponse"] & {
                            items?: components["schemas"]["User"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /**
         * Create an account with a role
         * @description The only way a staff or admin account comes into existence.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserCreate"];
                };
            };
            responses: {
                /** @description Created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update an account
         * @description Accounts are deactivated, never deleted. Deleting one would orphan the
         *     audit trail and the requests it acted on. Set `is_active: false` instead.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    user_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserUpdate"];
                };
            };
            responses: {
                /** @description Updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/api/admin/routing-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List routing rules */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All rules, active and inactive. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RoutingRule"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        /**
         * Replace the routing table
         * @description Replaces the full set in one transaction, because the routing screen edits
         *     the table as a whole. At most one active rule per category. Routing must
         *     be deterministic, and two active rules would leave the choice to
         *     insertion order. Superseded rules are deactivated, not deleted.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        rules: components["schemas"]["RoutingRuleInput"][];
                    };
                };
            };
            responses: {
                /** @description The rules now in effect. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RoutingRule"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description More than one active rule for the same category. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                422: components["responses"]["ValidationError"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the audit log
         * @description Append-only. There is no endpoint that edits or deletes an entry.
         */
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["Limit"];
                    offset?: components["parameters"]["Offset"];
                    actor_id?: string;
                    action?: string;
                    object_type?: string;
                    date_from?: string;
                    date_to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of entries, newest first. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedResponse"] & {
                            items?: components["schemas"]["AuditLogEntry"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /**
                 * @description Stable machine-readable identifier. Safe to branch on.
                 * @example not_found
                 * @example forbidden
                 * @example validation_error
                 * @example invalid_transition
                 */
                code: string;
                /** @description Human-readable, safe to show a barangay staff member. */
                message: string;
                /** @description Per-field problems, present on validation errors. */
                details?: {
                    /** @example description */
                    field: string;
                    /** @example Field is required. */
                    message: string;
                }[];
            };
        };
        PaginatedResponse: {
            items: unknown[];
            /** @description Total matching rows, ignoring limit and offset. */
            total: number;
            limit: number;
            offset: number;
        };
        /** @enum {string} */
        Role: "citizen" | "staff" | "admin";
        /**
         * @description A learned model output, not derived from keywords or rules.
         * @enum {string}
         */
        Urgency: "low" | "medium" | "high";
        /**
         * @description `submitted` on creation. Then either `classified` → `routed` when both
         *     confidence scores clear the threshold, or `under_review` when either does
         *     not. From `routed`: `in_progress` → `resolved` → `closed`.
         * @enum {string}
         */
        RequestStatus: "submitted" | "classified" | "routed" | "under_review" | "in_progress" | "resolved" | "closed";
        User: {
            /**
             * Format: uuid
             * @description UUID rather than a sequential integer. This is the only table holding
             *     personal data and its ids appear in URLs and audit records, so an
             *     authorization slip must not degrade into enumerating every resident.
             */
            id: string;
            /** Format: email */
            email: string;
            full_name: string;
            role: components["schemas"]["Role"];
            is_active: boolean;
            /** Format: date-time */
            created_at: string;
        };
        /** @description Identity only. Used where a full user record would leak PII. */
        UserSummary: {
            /** Format: uuid */
            id: string;
            full_name: string;
            role: components["schemas"]["Role"];
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
            full_name: string;
        };
        LoginRequest: {
            /**
             * Format: email
             * @description The account email. Named `username` by the auth library.
             */
            username: string;
            /** Format: password */
            password: string;
        };
        UserCreate: components["schemas"]["RegisterRequest"] & {
            role: components["schemas"]["Role"];
        };
        /** @description Only the supplied fields change. */
        UserUpdate: {
            full_name?: string;
            role?: components["schemas"]["Role"];
            is_active?: boolean;
        };
        Category: {
            id: number;
            /**
             * @description Stable machine identifier, and the exact label string used in the
             *     training dataset. Changing it desynchronises the model from the
             *     database.
             * @example road_infrastructure
             */
            slug: string;
            /** @description Display label. */
            name: string;
            /** @description What belongs in this category. Shown as help text. */
            description: string | null;
            is_active: boolean;
        };
        RequestCreate: {
            /** @description Free text in Filipino, English, or a mix. */
            description: string;
        };
        /** @description List rows. Enough for the staff queue without loading history. */
        RequestSummary: {
            id: number;
            /** @example GAB-2026-00042 */
            reference_number: string;
            description: string;
            /** @description Effective category. The human label if set, otherwise the prediction. */
            category: components["schemas"]["Category"] | null;
            /** @description Effective urgency, same rule as `category`. */
            urgency: components["schemas"]["Urgency"] | null;
            /** Format: float */
            category_confidence: number | null;
            /**
             * Format: float
             * @description Carried on list rows so the staff queue can show confidence without a
             *     detail fetch per row. Surfacing the score makes the classifier legible
             *     to the operator rather than opaque.
             */
            urgency_confidence: number | null;
            status: components["schemas"]["RequestStatus"];
            assigned_staff: components["schemas"]["UserSummary"] | null;
            /** Format: date-time */
            created_at: string;
        };
        /**
         * @description Nullable fields are always present in the response, carrying `null` when
         *     unset. They are listed as required so a client cannot confuse "absent"
         *     with "not yet classified".
         */
        Request: {
            id: number;
            /**
             * @description Human-readable handle a resident can quote in person or by phone.
             *     Drawn from a database sequence, so gaps after a rolled-back
             *     transaction are expected and not a defect.
             * @example GAB-2026-00042
             */
            reference_number: string;
            citizen: components["schemas"]["UserSummary"];
            description: string;
            /** @description Null until classification runs. */
            predicted_category: components["schemas"]["Category"] | null;
            predicted_urgency: components["schemas"]["Urgency"] | null;
            /** Format: float */
            category_confidence: number | null;
            /**
             * Format: float
             * @description Scored independently of the category head. A request is auto-routed
             *     only if `min(category_confidence, urgency_confidence)` meets the
             *     threshold, one gate over both labels, so a request is never routed
             *     on a label the model was unsure of.
             */
            urgency_confidence: number | null;
            /**
             * @description Stays null unless a human sets it. Null therefore means "no human has
             *     labelled this", which is distinct from "a human agreed with the
             *     model". Collapsing the two would erase the correction record.
             */
            final_category: components["schemas"]["Category"] | null;
            final_urgency: components["schemas"]["Urgency"] | null;
            /** @description Effective value. `final_category` if set, otherwise `predicted_category`. */
            category: components["schemas"]["Category"] | null;
            /** @description Effective value, same rule as `category`. */
            urgency: components["schemas"]["Urgency"] | null;
            status: components["schemas"]["RequestStatus"];
            assigned_staff: components["schemas"]["UserSummary"] | null;
            /**
             * @description Identifier of the exported model that produced the prediction, matching
             *     the run name recorded during training. Without it, predictions made
             *     before and after a retrain are indistinguishable.
             */
            model_version: string | null;
            /** Format: date-time */
            classified_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            resolved_at: string | null;
            attachments: components["schemas"]["Attachment"][];
            /** @description Oldest first. Drives the citizen-facing status timeline. */
            status_history: components["schemas"]["StatusHistoryEntry"][];
        };
        StatusUpdate: {
            /**
             * @description Deliberately narrower than `RequestStatus`. The earlier statuses are
             *     set by the system during classification and routing, so a staff UI
             *     should not be able to offer them. The illegal option is unrepresentable
             *     in the client rather than rejected by the server at runtime.
             * @enum {string}
             */
            to_status: "in_progress" | "resolved" | "closed";
            /** @description Resolution note or reason. Shown to the citizen. */
            note?: string;
        };
        StatusHistoryEntry: {
            id: number;
            /** @description Null on the first entry, which has no predecessor. */
            from_status: components["schemas"]["RequestStatus"] | null;
            to_status: components["schemas"]["RequestStatus"];
            /** @description Null when the system made the transition, e.g. auto-routing. */
            actor: components["schemas"]["UserSummary"] | null;
            note: string | null;
            /** Format: date-time */
            created_at: string;
        };
        ReviewDecision: {
            final_category_id: number;
            final_urgency: components["schemas"]["Urgency"];
            note?: string;
        };
        Attachment: {
            id: number;
            /** @description Original name, sanitised. Never used as the storage path. */
            filename: string;
            mime_type: string;
            size_bytes: number;
            /** Format: date-time */
            uploaded_at: string;
        };
        RoutingRule: {
            id: number;
            category: components["schemas"]["Category"];
            staff: components["schemas"]["UserSummary"];
            is_active: boolean;
        };
        RoutingRuleInput: {
            category_id: number;
            /** Format: uuid */
            staff_id: string;
        };
        AuditLogEntry: {
            id: number;
            /** @description Null when the system acted, e.g. auto-classification or auto-routing. */
            actor: components["schemas"]["UserSummary"] | null;
            /**
             * @example request.status_changed
             * @example user.deactivated
             * @example routing_rules.replaced
             */
            action: string;
            /** @example request */
            object_type: string;
            object_id: string | null;
            /** @description Action-specific context, e.g. before and after values. */
            detail: {
                [key: string]: unknown;
            } | null;
            /**
             * @description Retained for attributability. Personal data under RA 10173, collected
             *     because an audit trail that cannot be attributed is not an audit trail.
             */
            ip_address: string | null;
            /** Format: date-time */
            created_at: string;
        };
        Notification: {
            id: number;
            /** @description Null for notices not tied to a request. */
            request_id: number | null;
            /** @description Denormalised so the list renders without an extra fetch. */
            reference_number: string | null;
            message: string;
            is_read: boolean;
            /** Format: date-time */
            created_at: string;
        };
    };
    responses: {
        /** @description No session, or the session has expired. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authenticated, but the role does not permit this action. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description No such resource, or it exists outside the caller's scope. The two are
         *     deliberately indistinguishable.
         */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Conflicts with existing state, e.g. the email is taken. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The body failed validation. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Limit: number;
        Offset: number;
        RequestId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
