/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a citizen account
         * @description Self-registration always creates a `citizen`. Staff and admin accounts are
         *     created by an admin via `POST /api/admin/users`; a `role` sent here is
         *     ignored rather than honoured, so this endpoint cannot be used to escalate.
         *
         *     The account starts with `approval_status: pending`. It can sign in, but
         *     until staff approve it through `PATCH /api/registrations/{user_id}`,
         *     every route except `/api/auth/me`, password change and logout answers
         *     403. Only someone holding the password learns the account is pending.
         *
         *     `terms_version` is the version of the Terms of Use and Privacy Notice the
         *     person was shown, and must equal `terms_version` from `GET /api/site`. An older version answers 409, so a page loaded before
         *     the notice changed can't sign someone up to text they never saw.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Account created. Does not log the user in. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /**
                 * @description The email is taken, or `terms_version` is not the current one (detail
                 *     code `TERMS_OUTDATED`).
                 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a session
         * @description Sets an HttpOnly, Secure, SameSite=Lax session cookie. No token is
         *     returned in the body, and nothing is stored in `localStorage`. A token
         *     readable by JavaScript is XSS-exposed.
         *
         *     The body is form-encoded, not JSON, and the email goes in the `username`
         *     field. This is the one deviation from the JSON convention: it matches the
         *     `fastapi-users` default so the login route needs no custom code.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Session established; cookie set. */
                204: {
                    headers: {
                        /** @example gabai_session=...; HttpOnly; Secure; SameSite=Lax; Path=/ */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad credentials, or the account is deactivated. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session cleared. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user
         * @description Works while `must_change_password` is set, so the client can tell the
         *     person to change it. Everything else except `PUT /api/auth/password` and
         *     logout answers 403 until they do.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The authenticated user. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept the current Terms of Use and Privacy Notice
         * @description Records that the signed-in person accepted `version`, with the time.
         *     Works while acceptance is missing or out of date, like `/api/auth/me`.
         *     Until the account's accepted version matches `terms_version` from
         *     `GET /api/site`, every other route except `/api/auth/me`, password change
         *     and logout answers 403. When the notice changes, the version changes, and
         *     everyone is asked again at their next visit. Writes an audit row,
         *     `user.terms_accepted`, with the version.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TermsAcceptance"];
                };
            };
            responses: {
                /** @description Accepted. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Not the current version. Reload and read it again. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Change your own password
         * @description Changes the password of the signed-in account. An admin changing someone
         *     else's password uses `POST /api/admin/users/{user_id}/password` instead.
         *
         *     No audit row is written. Changing your own password crosses no
         *     privilege boundary.
         *
         *     Existing session cookies stay valid until they expire. The session is
         *     signed rather than stored server-side, so there is nothing to revoke.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PasswordChange"];
                };
            };
            responses: {
                /** @description Password changed. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The current password is wrong. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Email a password reset link
         * @description Always 202, whether or not the address has an account, so the form
         *     can't be used to find out who's registered. A link goes out only to a
         *     confirmed address, since an unconfirmed one might belong to someone
         *     else. One email per address every two minutes. The link carries the
         *     token after `#` so it never reaches server logs, and it stops working
         *     once the password changes.
         *
         *     Paths under `/api/auth` that are verbs come from the auth library, like
         *     login and logout. Everything written for this system is a noun.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EmailOnly"];
                };
            };
            responses: {
                /** @description Accepted. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set a new password from an emailed link
         * @description Same password rules as everywhere else. Clears `must_change_password`,
         *     since the person chose this one. Existing sessions stay valid.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PasswordReset"];
                };
            };
            responses: {
                /** @description Password changed. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /**
                 * @description `detail` is `RESET_PASSWORD_BAD_TOKEN` for an expired or used link,
                 *     or an object `{code: RESET_PASSWORD_INVALID_PASSWORD, reason}` when
                 *     the new password breaks the rules.
                 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/request-verify-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Email a link to confirm the address
         * @description Always 202. Sent automatically at sign-up; this resends it. Same
         *     two-minute limit per address. The link lasts 24 hours.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EmailOnly"];
                };
            };
            responses: {
                /** @description Accepted. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm an email address from the emailed link */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TokenOnly"];
                };
            };
            responses: {
                /** @description Confirmed. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description `VERIFY_USER_BAD_TOKEN` or `VERIFY_USER_ALREADY_VERIFIED`. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List requests, scoped to the caller's role
         * @description Scope is applied server-side and cannot be widened by query parameters:
         *
         *     - **citizen**, only their own requests
         *     - **staff**, requests assigned to them, plus requests in a category they
         *       hold an active routing rule for, plus everything in `under_review`. The
         *       union matters twice: deactivating a rule must not strip a staff member
         *       of requests already assigned to them, and a request awaiting manual
         *       classification cannot be scoped by a category that does not exist yet.
         *     - **admin**, all requests
         *
         *     The `under_review` clause is a deliberate widening of least privilege.
         *     Unclassified requests are visible to all staff because the category that
         *     would otherwise scope them is exactly what is in doubt; every review
         *     decision is attributed in the audit log.
         *
         *     Default ordering is role-dependent and chosen by the server, not the
         *     client. Staff and admin get highest urgency first, then oldest first,
         *     which is the order the queue is worked in. Citizens get newest first, because
         *     a resident opening their list is looking for the request they just
         *     filed, not the most urgent one.
         */
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["Limit"];
                    offset?: components["parameters"]["Offset"];
                    /** @description Repeat the parameter to match any of several statuses. */
                    status?: components["schemas"]["RequestStatus"][];
                    category_id?: number;
                    urgency?: components["schemas"]["Urgency"];
                    /** @description Case-insensitive substring match on description and reference number. */
                    q?: string;
                    sort?: "urgency_desc" | "created_asc" | "created_desc" | "updated_desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of requests. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedResponse"] & {
                            items?: components["schemas"]["RequestSummary"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /**
         * Submit a request
         * @description Persists the request and returns it immediately with status `submitted`
         *     and a reference number. Classification runs after the response, so the
         *     citizen never waits on inference; poll the detail endpoint (or watch
         *     notifications) for the classified result.
         *
         *     Only authenticated citizens may submit.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RequestCreate"];
                };
            };
            responses: {
                /** @description Accepted and persisted. Not yet classified. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Request"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        /**
         * Request detail
         * @description Same role scoping as `GET /api/requests`, including the `under_review`
         *     clause. Otherwise every row in the review queue would 404 on click.
         *
         *     Returns 404, not 403, when the request exists but is outside the caller's
         *     scope. A 403 would confirm the id is real and let a staff member map
         *     requests outside their categories by probing ids.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    request_id: components["parameters"]["RequestId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The request, with its status history and attachments. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Request"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{request_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change status
         * @description Staff and admin only. Writes a `status_history` row and an audit entry,
         *     and notifies the citizen. Illegal transitions are rejected with 409.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    request_id: components["parameters"]["RequestId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StatusUpdate"];
                };
            };
            responses: {
                /** @description Updated request. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Request"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description Not a legal transition from the current status. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                422: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/api/requests/{request_id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Attach a file
         * @description The owning citizen, or staff assigned to the request. MIME type and size
         *     are validated server-side against the declared allowlist. The `accept`
         *     attribute on a file input is a hint to the user, not a control.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    request_id: components["parameters"]["RequestId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description Stored. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Attachment"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description File exceeds the maximum size. */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description MIME type not allowed. */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{request_id}/attachments/{attachment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: components["parameters"]["RequestId"];
                attachment_id: number;
            };
            cookie?: never;
        };
        /**
         * Download an attachment
         * @description Scoped exactly as the parent request, so a file is never reachable by
         *     anyone who cannot see the request itself. Served through the API rather
         *     than as a static URL. `stored_path` is deliberately not exposed, so an
         *     unguessable-URL scheme is not standing in for an access check.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    request_id: components["parameters"]["RequestId"];
                    attachment_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description File contents. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": string;
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Requests awaiting manual classification
         * @description Staff and admin. Requests whose lower confidence score fell below the
         *     threshold and which therefore have status `under_review`, plus any request
         *     still at `submitted` two minutes after it was sent, meaning its
         *     classification never finished. Oldest first, because this queue is a
         *     backlog and urgency here is not yet trustworthy.
         */
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["Limit"];
                    offset?: components["parameters"]["Offset"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of requests needing a human label. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedResponse"] & {
                            items?: components["schemas"]["RequestSummary"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{request_id}/classification": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set the final category and urgency
         * @description Staff and admin. Sets `final_category_id` and `final_urgency`, then
         *     re-runs routing.
         *
         *     Works on **any** request the caller can see, not only items in the review
         *     queue, because the case where correction matters most is when the model
         *     was confident and wrong, and that request never reaches the queue. The
         *     model's original prediction is never overwritten, so every correction
         *     stays measurable against it.
         *
         *     **Re-routing can hand the request to someone else.** Changing the
         *     category re-runs the routing rules, so a request may be reassigned to a
         *     different staff member, after which the correcting staff member no
         *     longer sees it, because it is no longer theirs. That is intended: they
         *     handed it off. The citizen is notified of the reassignment.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    request_id: components["parameters"]["RequestId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReviewDecision"];
                };
            };
            responses: {
                /** @description Labelled and routed. `assigned_staff` may differ from before the call. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Request"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /**
                 * @description Request is `resolved` or `closed`. A finished request is not
                 *     relabelled. Re-routing one would resurrect it into an active queue.
                 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /**
                 * @description The body failed validation, or `final_category_id` is not a category
                 *     that exists and is switched on.
                 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List categories
         * @description The single source of category values for the whole system. Clients render
         *     whatever this returns; the taxonomy can change without a frontend release.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Admin only. Retired categories still appear on historical requests. */
                    include_inactive?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Categories, ordered by name. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's notifications */
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["Limit"];
                    offset?: components["parameters"]["Offset"];
                    unread_only?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of notifications, newest first. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedResponse"] & {
                            items?: components["schemas"]["Notification"][];
                            /** @description Total unread for this user, independent of paging. */
                            unread_count: number;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark as read */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    notification_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Updated notification. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Notification"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/api/registrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List resident sign-ups by approval status
         * @description Staff and admins. Citizens only, oldest first, so whoever signed up
         *     first gets checked first. Defaults to `pending`.
         */
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["Limit"];
                    offset?: components["parameters"]["Offset"];
                    status?: "pending" | "rejected";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of sign-ups. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedResponse"] & {
                            items?: components["schemas"]["User"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/registrations/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Approve or turn down a resident sign-up
         * @description Staff and admins. Citizens only. A turned-down sign-up can be approved
         *     later, so a mistake is not permanent. An approved account can't be
         *     turned down here, since that would let staff lock residents out, which
         *     is an admin's call through `PATCH /api/admin/users/{user_id}`. Approving
         *     needs a confirmed email while `REQUIRE_VERIFIED_EMAIL` is on, 409
         *     otherwise. Writes an audit row, `user.approved` or `user.rejected`.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    user_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegistrationDecision"];
                };
            };
            responses: {
                /** @description Decided. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description No citizen account with that id. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                409: components["responses"]["Conflict"];
            };
        };
        trace?: never;
    };
    "/api/site": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The barangay's details and the site's look
         * @description Public, because the masthead and footer show before anyone signs in.
         *     Contact fields are null until an admin fills them in, and the client
         *     hides a null field rather than showing a guess. `terms_version` is the
         *     Terms of Use and Privacy Notice version that sign-up and
         *     `POST /api/auth/terms` must send.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current settings. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SiteSettings"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/site/logo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The uploaded logo
         * @description Public. 404 when no logo has been uploaded, in which case the client
         *     shows the default. Clients add `logo_version` as a query parameter so a
         *     new upload isn't hidden by the browser cache.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The image. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/png": unknown;
                        "image/jpeg": unknown;
                        "image/webp": unknown;
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List accounts */
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["Limit"];
                    offset?: components["parameters"]["Offset"];
                    role?: components["schemas"]["Role"];
                    is_active?: boolean;
                    /** @description Case-insensitive substring match on email and full name. */
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of accounts. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedResponse"] & {
                            items?: components["schemas"]["User"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /**
         * Create an account with a role
         * @description The only way a staff or admin account comes into existence.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserCreate"];
                };
            };
            responses: {
                /** @description Created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update an account
         * @description Accounts are deactivated, never deleted. Deleting one would orphan the
         *     audit trail and the requests it acted on. Set `is_active: false` instead.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    user_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserUpdate"];
                };
            };
            responses: {
                /** @description Updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/api/admin/users/{user_id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset an account password
         * @description Issues a temporary password and returns it once, in this response. It is
         *     never stored unhashed and never appears in the audit log, which any admin
         *     can read. The admin reads it to the account holder, who changes it.
         *
         *     Writes an audit row with action `user.password_reset` and no detail.
         *     Sets `must_change_password`. The temporary password can still sign in,
         *     but that session can only change the password until it's replaced.
         *
         *     An admin may reset their own account, so there is no 409 here.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    user_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Password reset. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TemporaryPassword"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/routing-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List routing rules */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All rules, active and inactive. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RoutingRule"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        /**
         * Replace the routing table
         * @description Replaces the full set in one transaction, because the routing screen edits
         *     the table as a whole. At most one active rule per category. Routing must
         *     be deterministic, and two active rules would leave the choice to
         *     insertion order. Superseded rules are deactivated, not deleted. Every
         *     category must exist, and every newly assigned handler must be an active
         *     staff member or admin (422). A rule already in place is kept as is. If
         *     its handler was later deactivated or demoted, the rule stops routing and
         *     the category's requests go to the review queue.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        rules: components["schemas"]["RoutingRuleInput"][];
                    };
                };
            };
            responses: {
                /** @description The rules now in effect. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RoutingRule"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description More than one active rule for the same category. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /**
                 * @description The body failed validation, a category doesn't exist, or a newly
                 *     assigned handler isn't an active staff member or admin.
                 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/site": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change the barangay's details or the site's colour
         * @description Admin only. Send only the fields to change. `null` clears a contact
         *     field, which then disappears from the site. `theme` is one of the
         *     preset colours, each already checked for readable contrast, so no
         *     choice can make text unreadable. Writes an audit row, `site.updated`,
         *     listing the fields that changed.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SiteSettingsUpdate"];
                };
            };
            responses: {
                /** @description Updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SiteSettings"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                422: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/api/admin/site/logo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Upload a new logo
         * @description Admin only. PNG, JPEG or WebP, at most 1 MB. Replaces any earlier
         *     upload. Writes an audit row, `site.logo_changed`.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description Uploaded. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SiteSettings"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description Larger than 1 MB. */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not a PNG, JPEG or WebP image. */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Go back to the default logo
         * @description Admin only. Writes an audit row, `site.logo_removed`.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removed. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SiteSettings"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every category, including those switched off
         * @description Admin only. `GET /api/categories` lists only the ones switched on.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All categories. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Rename, describe, or switch a category on or off
         * @description Admin only. The `slug` never changes, because it is the label the
         *     classifier was trained on. There is no create or delete: the classifier
         *     can only predict the categories it was trained on, so a new one could
         *     never be chosen automatically. A request the classifier puts in a
         *     switched-off category goes to the review queue instead of being routed,
         *     and staff can't pick a switched-off category when relabelling. At least
         *     one category must stay on. Writes an audit row, `category.updated`,
         *     listing the fields that changed.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    category_id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CategoryUpdate"];
                };
            };
            responses: {
                /** @description Updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description This would switch off the last category that is on. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                422: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/api/admin/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the audit log
         * @description Append-only. There is no endpoint that edits or deletes an entry.
         */
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["Limit"];
                    offset?: components["parameters"]["Offset"];
                    actor_id?: string;
                    action?: string;
                    object_type?: string;
                    date_from?: string;
                    date_to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of entries, newest first. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedResponse"] & {
                            items?: components["schemas"]["AuditLogEntry"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /**
                 * @description Stable machine-readable identifier. Safe to branch on.
                 * @example not_found
                 * @example forbidden
                 * @example validation_error
                 * @example invalid_transition
                 */
                code: string;
                /** @description Human-readable, safe to show a barangay staff member. */
                message: string;
                /** @description Per-field problems, present on validation errors. */
                details?: {
                    /** @example description */
                    field: string;
                    /** @example Field is required. */
                    message: string;
                }[];
            };
        };
        PaginatedResponse: {
            items: unknown[];
            /** @description Total matching rows, ignoring limit and offset. */
            total: number;
            limit: number;
            offset: number;
        };
        EmailOnly: {
            /** Format: email */
            email: string;
        };
        TokenOnly: {
            token: string;
        };
        PasswordReset: {
            token: string;
            /** Format: password */
            password: string;
        };
        RegistrationDecision: {
            /** @enum {string} */
            approval_status: "approved" | "rejected";
        };
        /**
         * @description Staff and admin accounts are always `approved`.
         * @enum {string}
         */
        ApprovalStatus: "pending" | "approved" | "rejected";
        /** @enum {string} */
        Role: "citizen" | "staff" | "admin";
        /**
         * @description A learned model output, not derived from keywords or rules.
         * @enum {string}
         */
        Urgency: "low" | "medium" | "high";
        /**
         * @description `submitted` on creation. Then either `classified` → `routed` when both
         *     confidence scores clear the threshold, or `under_review` when either does
         *     not. From `routed`: `in_progress` → `resolved` → `closed`.
         * @enum {string}
         */
        RequestStatus: "submitted" | "classified" | "routed" | "under_review" | "in_progress" | "resolved" | "closed";
        User: {
            /**
             * Format: uuid
             * @description UUID rather than a sequential integer. This is the only table holding
             *     personal data and its ids appear in URLs and audit records, so an
             *     authorization slip must not degrade into enumerating every resident.
             */
            id: string;
            /** Format: email */
            email: string;
            full_name: string;
            role: components["schemas"]["Role"];
            is_active: boolean;
            /** @description The person clicked the link emailed to this address. */
            is_verified: boolean;
            approval_status: components["schemas"]["ApprovalStatus"];
            /**
             * @description Purok or street, as the resident typed it at sign-up. Only there so
             *     staff can confirm the person lives in the barangay. Null for staff
             *     and admin accounts.
             */
            residence?: string | null;
            /**
             * @description Set when an admin creates the account or resets its password, cleared
             *     when the person sets their own. Enforced server-side.
             */
            must_change_password: boolean;
            /**
             * @description The Terms of Use and Privacy Notice version this person last accepted.
             *     Null for accounts made before acceptance was recorded. When it differs
             *     from `terms_version` in `GET /api/site`, the client asks them to accept.
             */
            terms_accepted_version: string | null;
            /** Format: date-time */
            terms_accepted_at: string | null;
            /** Format: date-time */
            created_at: string;
        };
        /** @description Identity only. Used where a full user record would leak PII. */
        UserSummary: {
            /** Format: uuid */
            id: string;
            full_name: string;
            role: components["schemas"]["Role"];
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
            full_name: string;
            /** @description Purok or street, so staff can confirm residency. */
            residence: string;
            /** @description The Terms of Use and Privacy Notice version the person accepted. */
            terms_version: string;
        };
        TermsAcceptance: {
            version: string;
        };
        LoginRequest: {
            /**
             * Format: email
             * @description The account email. Named `username` by the auth library.
             */
            username: string;
            /** Format: password */
            password: string;
        };
        /** @description Admin-created accounts are approved from the start. */
        UserCreate: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
            full_name: string;
            role: components["schemas"]["Role"];
        };
        /** @description Only the supplied fields change. A name is trimmed, and a change of name is recorded in the audit log as `user.renamed`, without the names. */
        UserUpdate: {
            full_name?: string;
            role?: components["schemas"]["Role"];
            is_active?: boolean;
        };
        PasswordChange: {
            /** Format: password */
            current_password: string;
            /** Format: password */
            new_password: string;
        };
        /**
         * @description Returned once and never again. The plaintext exists only in this response
         *     body; the stored value is hashed like any other password.
         */
        TemporaryPassword: {
            /**
             * @description Ten characters from an alphabet with `0`, `O`, `1`, `l` and `I`
             *     removed, because someone reads this aloud at a shared desk.
             */
            temporary_password: string;
        };
        Category: {
            id: number;
            /**
             * @description Stable machine identifier, and the exact label string used in the
             *     training dataset. Changing it desynchronises the model from the
             *     database.
             * @example road_infrastructure
             */
            slug: string;
            /** @description Display label. */
            name: string;
            /** @description What belongs in this category. Shown as help text. */
            description: string | null;
            is_active: boolean;
        };
        /** @description Send only the fields to change. */
        CategoryUpdate: {
            name?: string;
            description?: string | null;
            is_active?: boolean;
        };
        /**
         * @description A preset main colour. Each has at least 5:1 contrast with white, since
         *     the colour is used both behind white text and as text.
         * @enum {string}
         */
        ThemePreset: "green" | "blue" | "maroon" | "teal" | "purple" | "brown";
        SiteSettings: {
            /** @example Barangay V (Singko) */
            barangay_name: string;
            /** @example Amaya, Tanza, Cavite */
            place: string;
            address: string | null;
            hotline: string | null;
            office_hours: string | null;
            theme: components["schemas"]["ThemePreset"];
            /** @description Changes with every upload. Null means no upload, so use the default logo. */
            logo_version: string | null;
            /** @description The current Terms of Use and Privacy Notice version. */
            terms_version: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description Send only the fields to change. `null` clears a contact field. */
        SiteSettingsUpdate: {
            barangay_name?: string;
            place?: string;
            address?: string | null;
            hotline?: string | null;
            office_hours?: string | null;
            theme?: components["schemas"]["ThemePreset"];
        };
        RequestCreate: {
            /** @description Free text in Filipino, English, or a mix. */
            description: string;
        };
        /** @description List rows. Enough for the staff queue without loading history. */
        RequestSummary: {
            id: number;
            /** @example GAB-2026-00042 */
            reference_number: string;
            description: string;
            /** @description Effective category. The human label if set, otherwise the prediction. */
            category: components["schemas"]["Category"] | null;
            /** @description Effective urgency, same rule as `category`. */
            urgency: components["schemas"]["Urgency"] | null;
            /** Format: float */
            category_confidence: number | null;
            /**
             * Format: float
             * @description Carried on list rows so the staff queue can show confidence without a
             *     detail fetch per row. Surfacing the score makes the classifier legible
             *     to the operator rather than opaque.
             */
            urgency_confidence: number | null;
            status: components["schemas"]["RequestStatus"];
            assigned_staff: components["schemas"]["UserSummary"] | null;
            /** Format: date-time */
            created_at: string;
        };
        /**
         * @description Nullable fields are always present in the response, carrying `null` when
         *     unset. They are listed as required so a client cannot confuse "absent"
         *     with "not yet classified".
         */
        Request: {
            id: number;
            /**
             * @description Human-readable handle a resident can quote in person or by phone.
             *     Drawn from a database sequence, so gaps after a rolled-back
             *     transaction are expected and not a defect.
             * @example GAB-2026-00042
             */
            reference_number: string;
            citizen: components["schemas"]["UserSummary"];
            description: string;
            /** @description Null until classification runs. */
            predicted_category: components["schemas"]["Category"] | null;
            predicted_urgency: components["schemas"]["Urgency"] | null;
            /** Format: float */
            category_confidence: number | null;
            /**
             * Format: float
             * @description Scored independently of the category head. A request is auto-routed
             *     only if `min(category_confidence, urgency_confidence)` meets the
             *     threshold, one gate over both labels, so a request is never routed
             *     on a label the model was unsure of.
             */
            urgency_confidence: number | null;
            /**
             * @description Stays null unless a human sets it. Null therefore means "no human has
             *     labelled this", which is distinct from "a human agreed with the
             *     model". Collapsing the two would erase the correction record.
             */
            final_category: components["schemas"]["Category"] | null;
            final_urgency: components["schemas"]["Urgency"] | null;
            /** @description Effective value. `final_category` if set, otherwise `predicted_category`. */
            category: components["schemas"]["Category"] | null;
            /** @description Effective value, same rule as `category`. */
            urgency: components["schemas"]["Urgency"] | null;
            status: components["schemas"]["RequestStatus"];
            assigned_staff: components["schemas"]["UserSummary"] | null;
            /**
             * @description Identifier of the exported model that produced the prediction, matching
             *     the run name recorded during training. Without it, predictions made
             *     before and after a retrain are indistinguishable.
             */
            model_version: string | null;
            /** Format: date-time */
            classified_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            resolved_at: string | null;
            attachments: components["schemas"]["Attachment"][];
            /** @description Oldest first. Drives the citizen-facing status timeline. */
            status_history: components["schemas"]["StatusHistoryEntry"][];
        };
        StatusUpdate: {
            /**
             * @description Deliberately narrower than `RequestStatus`. The earlier statuses are
             *     set by the system during classification and routing, so a staff UI
             *     should not be able to offer them. The illegal option is unrepresentable
             *     in the client rather than rejected by the server at runtime.
             * @enum {string}
             */
            to_status: "in_progress" | "resolved" | "closed";
            /** @description Resolution note or reason. Shown to the citizen. */
            note?: string;
        };
        StatusHistoryEntry: {
            id: number;
            /** @description Null on the first entry, which has no predecessor. */
            from_status: components["schemas"]["RequestStatus"] | null;
            to_status: components["schemas"]["RequestStatus"];
            /** @description Null when the system made the transition, e.g. auto-routing. */
            actor: components["schemas"]["UserSummary"] | null;
            note: string | null;
            /** Format: date-time */
            created_at: string;
        };
        ReviewDecision: {
            final_category_id: number;
            final_urgency: components["schemas"]["Urgency"];
            note?: string;
        };
        Attachment: {
            id: number;
            /** @description Original name, sanitised. Never used as the storage path. */
            filename: string;
            mime_type: string;
            size_bytes: number;
            /** Format: date-time */
            uploaded_at: string;
        };
        RoutingRule: {
            id: number;
            category: components["schemas"]["Category"];
            staff: components["schemas"]["UserSummary"];
            is_active: boolean;
        };
        RoutingRuleInput: {
            category_id: number;
            /** Format: uuid */
            staff_id: string;
        };
        AuditLogEntry: {
            id: number;
            /** @description Null when the system acted, e.g. auto-classification or auto-routing. */
            actor: components["schemas"]["UserSummary"] | null;
            /**
             * @example request.status_changed
             * @example user.deactivated
             * @example routing_rules.replaced
             */
            action: string;
            /** @example request */
            object_type: string;
            object_id: string | null;
            /** @description Action-specific context, e.g. before and after values. */
            detail: {
                [key: string]: unknown;
            } | null;
            /**
             * @description Retained for attributability. Personal data under RA 10173, collected
             *     because an audit trail that cannot be attributed is not an audit trail.
             */
            ip_address: string | null;
            /** Format: date-time */
            created_at: string;
        };
        Notification: {
            id: number;
            /** @description Null for notices not tied to a request. */
            request_id: number | null;
            /** @description Denormalised so the list renders without an extra fetch. */
            reference_number: string | null;
            message: string;
            is_read: boolean;
            /** Format: date-time */
            created_at: string;
        };
    };
    responses: {
        /** @description No session, or the session has expired. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Authenticated, but not allowed. The role does not permit this action,
         *     the account is still waiting for approval, it is on a temporary
         *     password and has to change it first, or it hasn't accepted the current
         *     Terms of Use and Privacy Notice.
         */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description No such resource, or it exists outside the caller's scope. The two are
         *     deliberately indistinguishable.
         */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Conflicts with existing state, e.g. the email is taken. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The body failed validation. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Limit: number;
        Offset: number;
        RequestId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
