"""create routing rules table

Revision ID: 2e4df1b9ff8f
Revises: e55587331207
Create Date: 2026-09-07 14:03:10.687946

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2e4df1b9ff8f'
down_revision: str | None = 'e55587331207'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routing_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_routing_rules_one_active_per_category', 'routing_rules', ['category_id'], unique=True, postgresql_where=sa.text('is_active'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_routing_rules_one_active_per_category', table_name='routing_rules', postgresql_where=sa.text('is_active'))
    op.drop_table('routing_rules')
    # ### end Alembic commands ###
