"""create categories table

Revision ID: 3b2ac3a01749
Revises: 7e6e785eb361
Create Date: 2026-09-06 20:55:08.942115

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3b2ac3a01749'
down_revision: str | None = '7e6e785eb361'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

categories_table = sa.table(
    "categories",
    sa.column("id", sa.Integer),
    sa.column("slug", sa.String),
    sa.column("name", sa.String),
    sa.column("description", sa.String),
    sa.column("is_active", sa.Boolean),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###

    op.bulk_insert(
        categories_table,
        [
            {"slug": "road_infrastructure", "name": "Road & Infrastructure", "description": "Potholes, damaged roads, bridges, streetlights, drainage structures", "is_active": True},
            {"slug": "public_health_sanitation", "name": "Public Health & Sanitation", "description": "Garbage collection, stagnant water, pests, health center concerns", "is_active": True},
            {"slug": "public_safety", "name": "Public Safety & Peace and Order", "description": "Suspicious activity, hazards, curfew, stray animals", "is_active": True},
            {"slug": "utilities", "name": "Utilities", "description": "Water interruption, power, flooding, drainage blockage", "is_active": True},
            {"slug": "social_welfare", "name": "Social Welfare & Assistance", "description": "Ayuda, senior and PWD concerns, indigency, financial assistance", "is_active": True},
            {"slug": "neighbor_dispute", "name": "Neighbor Dispute & Nuisance", "description": "Noise, boundary, tenant, and other interpersonal concerns", "is_active": True},
            {"slug": "other", "name": "Other / General Inquiry", "description": "Anything that doesn't fit above", "is_active": True},
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    # ### end Alembic commands ###
