"""create requests table

Revision ID: 4cc16686e59a
Revises: 3b2ac3a01749
Create Date: 2026-09-06 21:09:07.381602

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4cc16686e59a'
down_revision: str | None = '3b2ac3a01749'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(length=20), nullable=False),
    sa.Column('citizen_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('predicted_category_id', sa.Integer(), nullable=True),
    sa.Column('predicted_urgency', sa.Enum('low', 'medium', 'high', name='urgency'), nullable=True),
    sa.Column('category_confidence', sa.Float(), nullable=True),
    sa.Column('urgency_confidence', sa.Float(), nullable=True),
    sa.Column('final_category_id', sa.Integer(), nullable=True),
    sa.Column('final_urgency', sa.Enum('low', 'medium', 'high', name='urgency'), nullable=True),
    sa.Column('status', sa.Enum('submitted', 'classified', 'routed', 'under_review', 'in_progress', 'resolved', 'closed', name='request_status'), nullable=False),
    sa.Column('assigned_staff_id', sa.UUID(), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('classified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['final_category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['predicted_category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    # ### end Alembic commands ###
