"""create status history entries table

Revision ID: e55587331207
Revises: 4cc16686e59a
Create Date: 2026-09-06 21:14:46.988089

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'e55587331207'
down_revision: str | None = '4cc16686e59a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_history_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('from_status', postgresql.ENUM('submitted', 'classified', 'routed', 'under_review', 'in_progress', 'resolved', 'closed', name='request_status', create_type=False), nullable=True),
    sa.Column('to_status', postgresql.ENUM('submitted', 'classified', 'routed', 'under_review', 'in_progress', 'resolved', 'closed', name='request_status', create_type=False), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status_history_entries')
    # ### end Alembic commands ###
